### ISSUE TITLE
Error with getPlayer()

### ISSUE THREAD

**Issue by Lajoie25** [clashperk/clashofclans.js#168]
Error when call getPlayer() with players below HT 10:

\CocTeams\node_modules\clashofclans.js\dist\struct\Unit.js:32
                this.level = origin.level;
                                    ^

TypeError: Cannot read properties of undefined (reading 'level')

in rawSuperUnit, I debug with this code to continue my app:

            if (origin) {
                this.level = origin.level;
                this.maxLevel = origin.maxLevel;
                this.boostable = data.townHallLevel >= 11 && origin.level >= rawSuperUnit.minOriginalLevel;
                this.upgradeCost = original.upgrade.cost[origin.level - 1] || 0;
                this.upgradeResource = original.upgrade.resource;
                this.upgradeTime = original.upgrade.time[origin.level - 1] || 0;
            }

**Comment by csuvajit** [comment]
Fixed

**Comment by dannycreations** [comment]
This is not fixed, you can check with this #Q9QRCUGU9
```
Barbarian { name: 'Barbarian', level: 6, maxLevel: 12, village: 'home' }
Archer { name: 'Archer', level: 8, maxLevel: 12, village: 'home' }
Wall Breaker { name: 'Wall Breaker', level: 4, maxLevel: 12, village: 'home' }
Giant { name: 'Giant', level: 4, maxLevel: 12, village: 'home' }
Goblin { name: 'Goblin', level: 4, maxLevel: 9, village: 'home' }
Miner { name: 'Miner', level: 1, maxLevel: 10, village: 'home' }
Balloon { name: 'Balloon', level: 8, maxLevel: 11, village: 'home' }
Baby Dragon { name: 'Baby Dragon', level: 1, maxLevel: 10, village: 'home' }
Valkyrie { name: 'Valkyrie', level: 1, maxLevel: 11, village: 'home' }
Witch { name: 'Witch', level: 4, maxLevel: 7, village: 'home' }
Lava Hound { name: 'Lava Hound', level: 1, maxLevel: 6, village: 'home' }
Bowler undefined
```

**Comment by csuvajit** [comment]
I see, fixed again.

**Comment by dannycreations** [comment]
fixed, thanks @csuvajit
