### ISSUE TITLE
Error in getPlayerRanks

### ISSUE THREAD

**Issue by tentententoten** [clashperk/clashofclans.js#72]
I created an account to post issues.
When I used getPlayerRanks, I got an error, probably due to an unaffiliated person who is not a member of the clan.
I hope this can be fixed.

**Comment by csuvajit** [comment]
Please post the stack trace.

**Comment by tentententoten** [comment]
It was my own misunderstanding due to the version.
I'm sorry.

**Comment by csuvajit** [comment]
Thank you. This issue has been fixed on version [2.0.2](https://github.com/clashperk/clashofclans.js/releases/tag/2.0.2)

**Comment by tentententoten** [comment]
Thank you!
