### ISSUE TITLE
We dont know how to use it

### ISSUE THREAD

**Issue by FlameQuard** [clashperk/clashofclans.js#8]
Can you make a bot of clash of clans for us please with more command

**Comment by kwiksilver3441** [comment]
It's odd, I recall there being a website with some examples of all the methods used, though I cannot find it anymore. 

> Can you make a bot of clash of clans for us please with more command
I went around this by viewing the Client.js in the source file of clashofclans.js in node_modules. It's not the best way to find the methods on how to use, but it's typical markup so it's easy to find what you're looking for. After that it's just basic js fetches.

Thanks for the package btw. Works well, but I agree documentation could be better considering it's hard to find the methods you can use and their exact names.

**Comment by csuvajit** [comment]
The documentation site still exists. https://clashofclans.js.org/api/
![image](https://user-images.githubusercontent.com/45002322/124893922-cda5a300-dff8-11eb-90ce-468dd7fc9dd0.png)

**Comment by kwiksilver3441** [comment]
Oh I see. I don't think that sidebar exists on mobile.

**Comment by csuvajit** [comment]
I've listed all available methods in readme.
https://github.com/clashperk/clashofclans.js#methods
